server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    tomcat:
      max-active: 100
  jackson:
    default-property-inclusion: non_null



#  mybatis.mapper-locations=classpath:mapper/*.xml
#
#  user.address.max-count=20
#
#  spring.jackson.default-property-inclusion=NON_NULL
mybatis:
  mapper-locations: classpath:mapper/*.xml


